[package]
name = "chrys-source-raster"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
chrys-source = { path = "../chrys-source" }
image = { workspace = true, features = ["png", "jpeg", "webp", "tiff"] }
thiserror.workspace = true
toml.workspace = true
serde.workspace = true
