[package]
name = "chrys-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "chrys"
path = "src/main.rs"

[dependencies]
chrys-source = { path = "../chrys-source" }
chrys-source-raster = { path = "../chrys-source-raster" }
chrys-source-sequence = { path = "../chrys-source-sequence" }
chrys-source-animation = { path = "../chrys-source-animation" }
chrys-core = { path = "../chrys-core" }
chrys-rule = { path = "../chrys-rule" }
clap.workspace = true
anyhow.workspace = true
